language: node_js
node_js:
  - "6"
addons:
  firefox: "49.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager update --standalone --firefox
  - webdriver-manager start 2>&1 &
  - sleep 10
script:  
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-49.0.2.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - npm start 2>&1 &
  - sleep 20
  - npm run tests-e2e