sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 6
  - 7
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run tests-e2e-prepare 2>&1 &
  - sleep 10
install:
  - npm install
script:  
  - npm start 2>&1 &
  - sleep 20
  - npm run tests-e2e